name = "BatchStats"
uuid = "fc354a49-c873-40ff-aa7e-af8a5c6a2882"
authors = ["Cees-Bart Breunesse <ceeesb@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.25.120"
HypothesisTests = "0.11.5"
LinearAlgebra = "1.11.0"
ProgressBars = "1.5.1"
Statistics = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
